#!/system/bin/sh
# this will give your conservative governor better performance
# but worse battery life


# cpu usage percentage above which the frequency will be sampled up
echo "65" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold

# cpu usage percentage below which the frequency will be sampled down
echo "25" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold

# rate at which to check the usage - now: 2.5 seconds
echo "2500000" > /sys/devices/system/cpu/cpufreq/conservative/sampling_rate

# multiplier of the above when sampling down - now: will sample down more slowly then up (2x2.5sec = 5sec)
echo "4" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor


#
# same explanations as for the above apply here
#
# be sure to change the values to the same numbers as the ones above
# they are in the same order (just in case)
#
echo "65" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/up_threshold
echo "25" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/down_threshold
echo "2500000" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/sampling_rate
echo "4" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/sampling_down_factor
