#!/system/bin/sh
# this will give your conservative governor better performance
# but worse battery life

echo "65" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold
echo "25" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold
echo "4" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor
echo "2500000" > /sys/devices/system/cpu/cpufreq/conservative/sampling_rate

echo "65" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/up_threshold
echo "25" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/down_threshold
echo "4" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/sampling_down_factor
echo "2500000" > /sys/devices/system/cpu/cpu0/cpufreq/conservative/sampling_rate
